---
abstract: 'PSGI engine for Limper'
author:
  - 'Ashley Willis <ashley+perl@gitable.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Limper-Engine-PSGI
provides:
  Limper:
    file: lib/Limper/Engine/PSGI.pm
    version: 0.001
  Limper::Engine::PSGI:
    file: lib/Limper/Engine/PSGI.pm
    version: 0.001
requires:
  Limper: 0.010
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  repository: https://gitable.org/ashley/limper-engine-psgi.git
version: 0.001
